src/encoding/__init__.py
src/encoding/addition.py
tests/test_encoding.py

Turns out we don't even need table lookup to do 8-bit addition like what we did in #9
Replace the table lookup with the simple linear combinations

Tableless addition checks

---

specs/introduction.md

We plan to move our written specs to the repo as the source of truth
- Create a `specs/` directory. All markdown specs go here
- TODO in future PR, add a parser to parse the Python code for testing.
Note to reviewers: Review the spec text but also the directory structure. As that's how we move future docs here

Add introduction

---

src/encoding/__init__.py
src/encoding/commitment.py
src/encoding/lookup.py
tests/test_encoding.py

We haven't described the commitment check yet, which checks 
- if an array x8s is an opening of a u256 commitment and 
- if elements in the x8s are all 8 bits.
- Adding the RangeTable for 8-bit value check
- add check_commitment
- and add testings

add commitment check

---

specs/lookup.md
src/encoding/lookup.py

In the spec, we don't have to specify how the table lookup commitment is actually created. The halo2 API can do this behind the scene. We can just define the table format like columns and rows.
- Remove the compress function in the python code lookup table
- Add a note on lookup table

revamp lookup table and note

---

src/zkevm_specs/evm/instruction.py
src/zkevm_specs/evm/table.py
src/zkevm_specs/evm/typing.py
src/zkevm_specs/util/__init__.py
src/zkevm_specs/util/arithmetic.py
src/zkevm_specs/util/param.py
tests/evm/test_add.py
tests/evm/test_begin_tx.py
tests/evm/test_jump.py
tests/evm/test_jumpi.py
tests/evm/test_push.py

This PR aims to add the missing block constant functionality of `Instruction`.
It adds a `block_table` to store all static block constant and up to previous 256 block hashes for block constant lookup. The table in real implementation could share the same instance columns with `tx_table` once they are properly separate by selectors.
This approach targets a straightforward implementation, in the future we could also adopt `EIP2935` mentioned in #75 to totally remove `block_table`.

Add `block_lookup` in `Instruction` for block constant access

---

src/zkevm_specs/evm/execution/add.py
src/zkevm_specs/evm/execution/begin_tx.py
src/zkevm_specs/evm/instruction.py
src/zkevm_specs/evm/step.py
src/zkevm_specs/evm/table.py
src/zkevm_specs/evm/typing.py
src/zkevm_specs/util/param.py
tests/evm/test_begin_tx.py

This PR aims to change the transaction format to legacy one, and defer support of dynamic gas price transaction introduced by `EIP1559` to the future work for simplicity.
It also does:
- Extend `add_word` to `add_words` to match current circuit implementation
- Add `CallDataGasCost` in `tx_table` for lookup to calculate the correct intrinsic gas cost for legacy tx

Use legacy transaction format and defer support of dynamic gas price

---

specs/opcode/33CALLER.md
src/zkevm_specs/evm/execution/__init__.py
src/zkevm_specs/evm/execution/caller.py
src/zkevm_specs/evm/main.py
tests/evm/test_caller.py

I have followed the pattern from https://github.com/appliedzkp/zkevm-specs/pull/83 but using the CallContext in the rw_table instead of the Block table for the value lookup.
Related issue: https://github.com/appliedzkp/zkevm-specs/issues/86
---
I've added two questions for doubts I had:
```
```

Add spec for CALLER opcode

---

specs/opcode/33CALLER.md
specs/opcode/34CALLVALUE.md
specs/opcode/36CALLDATASIZE.md
src/zkevm_specs/evm/execution/__init__.py
src/zkevm_specs/evm/execution/calldatasize.py
src/zkevm_specs/evm/execution/caller.py
src/zkevm_specs/evm/execution/callvalue.py
src/zkevm_specs/util/param.py
tests/evm/test_calldatasize.py
tests/evm/test_callvalue.py

Also fix rw_table order in CALLER: first call context, then stack op.
This makes the circuit closer to the actual EVM behaviour: first the
caller_address is obtained from the call context, and then it is pushed
to the stack.

Add CALLVALUE and CALLDATASIZE

---

src/zkevm_specs/evm/execution/begin_tx.py
src/zkevm_specs/evm/instruction.py
src/zkevm_specs/evm/step.py
tests/evm/test_begin_tx.py

This PR is once part of #82, and aims to move the tracking of `last_callee_*` to `rw_table` for simplicity.

Untrack `last_callee_*` of `StepState`

---

setup.cfg

The package black has a new update released, causing some confusion. The CI checks the formatting with the new version but the developers' local old versions disagree with the formatting.
We need to pin the versions of the packages to prevent CI from using a new version that we haven't explicitly upgraded.
Note: Run `make install` after this PR is merged.

upgrade and pin dependencies

---

setup.cfg
src/zkevm_specs/bytecode.py
src/zkevm_specs/evm/execution/begin_tx.py
src/zkevm_specs/evm/execution/slt_sgt.py
src/zkevm_specs/evm/instruction.py
src/zkevm_specs/evm/step.py
src/zkevm_specs/evm/table.py
src/zkevm_specs/evm/typing.py
src/zkevm_specs/util/__init__.py
src/zkevm_specs/util/arithmetic.py
tests/evm/test_add.py
tests/test_bytecode_circuit.py

Currently values in the Fp field all use int type in Python. There two drawbacks about this:
- There is potential overflow problem with int value
- Writing expression on these values requires to use `fp_add`, `fp_mul`, etc. It is quite annoying and makes the expression hard to understand.
Therefore, this PR replaces the values in the Fp field by `bn128_FQ` in the py-ecc package.

Change field value from int to field numbers

---

tests/evm/test_gasprice.py

For some reason the CI did not catch an fmt error in the code introduced in #119 
This PR fixes the formatting issues.

Fix gasprice.py formatting

---

specs/state-proof.md
specs/tables.md
src/zkevm_specs/evm/table.py
src/zkevm_specs/state.py
tests/test_state_circuit.py

- Update the state proof document
- Write the spec of the state circuit in python from scratch following
the current `rw_table` design.
- Add a minimal state circuit test
- List of changes:
- Renamed key and aux columns so start with index 0, in order to
make it more readable when working with code were we have arrays
called `keys`.  This way `key0` == `keys[0]`.
- Add a new key column so that we have a cloumn exclusive for
address keys, which allows us to reuse the key order constraints
for addresses for all operations.
- Add the boilerplate for the missing operations
- Remove value2 column (used for `valuePrev`) in some Write
operations

Redo spec of state circuit

---

src/zkevm_specs/state.py

It being 0 will cause us to hit the unreachable code in line 363 because 0 isn't one of the allowed values for `Tag`.

Don't allow key0 to be 0

---

src/zkevm_specs/evm/execution/begin_tx.py
src/zkevm_specs/evm/execution/storage.py
src/zkevm_specs/evm/instruction.py

Just realized using `is_warm` as value of access list in real circuit seems more straightforward, so this PR aims to revert the change made in #132, and also update the usage of access list in `BeginTx`.
(to be nitpicking, it should be `is_already_warm` or `is_warm_prev` since it's the previous value, but omitting `already` or `prev` seems fine here)

Use `is_warm` instead of `is_cold` for access list value

---

Makefile
setup.cfg

mdformat is not latex compatible and doesn't support ignore. We remove it to unblock #149

remove mdformat

---

src/zkevm_specs/state.py

2^32 is already a good upper bound. The maximum memory address that can be touched with the current gas limit of 30e6 is about 123,170, which sadly is just over 2^16.

Set MAX_KEY3 to MAX_MEMORY_ADDRESS

---

setup.cfg

There's a bug in the `black` that blocks the lint check in the CI (see [log](https://github.com/appliedzkp/zkevm-specs/runs/5725937215?check_suite_focus=true)). The bug is fixed in the `black` v22.3 (see [reference](https://github.com/psf/black/issues/2969)).

Update black version

---

setup.cfg
specs/transactions-proof.md
src/zkevm_specs/tx.py
tests/test_tx_circuit.py

The python spec corresponds to the first iteration of the transaction circuit, where we take some shortcuts described in the markdown document.  In particular
- The RLP of the transaction without signature is done outside of the circuit
- The hash of the RLP of the transaction without signature is done outside of the circuit, and is added into the transaction table so that the circuit can verify the signature.

Add tx circuit spec

---

src/zkevm_specs/tx.py

Today I merged https://github.com/appliedzkp/zkevm-specs/pull/150 and I broke the tests in master.  This is the fix

Fix tx circuit RLC usage with 64 bytes input

---

CODEOWNERS

Follows the rationale of https://github.com/appliedzkp/zkevm-circuits/pull/429

Add CODEOWNERS file to repo to automatically assign reviewers

---

src/zkevm_specs/evm/execution/copy_to_log.py
src/zkevm_specs/evm/execution/log.py
src/zkevm_specs/evm/step.py
src/zkevm_specs/util/param.py
tests/evm/test_logs.py

the circuit fix https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/510 has been merged ,  also change `MAX_COPY_BYTES` to 32 aligning with circuit implementation .

fix copy log data index in multi steps

---

src/zkevm_specs/evm/execution/copy_to_log.py
src/zkevm_specs/evm/execution/log.py
src/zkevm_specs/evm/instruction.py
tests/evm/test_logs.py

two minor changes:
1. use next step log_id ( current step 's log_id + 1) to look up logs fields.  
the reason is only in next copy step, log_id plus 1,  while current step log_id is zero,  however, for the semantic matter, they are belong to the same real step of evm/geth,  so both use next step log_id is reasonable for lookup, which also matched pre defined zero log id meaning no log data executed. 
3. add log static gas , which is done in circuit side https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/507

revise log id for look up

---

specs/copy-proof.md
specs/tables.md
src/zkevm_specs/copy_circuit.py
src/zkevm_specs/evm/execution/__init__.py
src/zkevm_specs/evm/execution/calldatacopy.py
src/zkevm_specs/evm/execution/codecopy.py
src/zkevm_specs/evm/execution/log.py
src/zkevm_specs/evm/execution/return_.py
src/zkevm_specs/evm/execution/sha3.py
src/zkevm_specs/evm/instruction.py
src/zkevm_specs/evm/table.py
src/zkevm_specs/evm/typing.py
src/zkevm_specs/util/param.py
src/zkevm_specs/util/testing.py
tests/evm/test_calldatacopy.py
tests/evm/test_codecopy.py
tests/evm/test_logs.py
tests/evm/test_return.py
tests/evm/test_sha3.py

This PR adds a `RlcAcc` type in the `CopyDataTypeTag` enum.
This tag is reserved for copy destination where instead of copying byte to byte (read to write), we're accumulating an RLC value in the destination. That is:
```
write_val::cur == (write_val::prev * r) + read_val::cur
```
This variant of the copy circuit will be used for `SHA3` opcode execution gadget, where the goal is to find a final accumulator value over each byte from the input. The final RLC accumulator will be used to lookup to the Keccak table and find the `SHA3` of the input bytes.
The PR also implements the `SHA3` opcode.
Closes #228 
Closes #223

SHA3 opcode | Keccak support in copy circuit

---

Makefile
src/zkevm_specs/public_inputs.py
src/zkevm_specs/state.py
src/zkevm_specs/tx.py
src/zkevm_specs/util/arithmetic.py

We defined duplicated `linear_combine` functions throughout the codebase.
We define a common `linear_combine` to make sure all circuits behave in the same way.

Unify RLC functions

---

src/zkevm_specs/copy_circuit.py
src/zkevm_specs/evm/execution/sha3.py
src/zkevm_specs/evm/typing.py
src/zkevm_specs/util/constraint_system.py
tests/evm/test_sha3.py

The following fixes have been made in this PR:
- Exceptions (eg. assertion) from within a `cs.condition` were not raised since the `__exit__` did not raise them. This meant, we were never warned about nested conditions not allowed, and any constraint failure within a condition was also completely ignored.
- `CALLDATACOPY` memory read was added even for `is_pad = True`
- Remove nested conditions
- `SHA3` gadget should do a copy table lookup only if `length > 0`. Otherwise `copy_rwc_inc = rlc_acc = 0`

fix: constraint system fix | related fixes in copy circuit

---

specs/tables.md
src/zkevm_specs/evm/execution/end_block.py
src/zkevm_specs/evm/instruction.py
src/zkevm_specs/evm/table.py
src/zkevm_specs/evm/typing.py
src/zkevm_specs/tx.py
tests/evm/test_end_block.py

The main change is using 2 strategic lookups to the padding rows with sequential numbers to prove a lower bound on padding rows which allows proving the number of rw operations in the rw_table and txs in the tx table; as devised by @z2trillion in https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/558
NOTE: To implement this spec, EndBlock needs to be height = 1, which can be achieved after reducing the number of cells used in the state selector in the EVM circuit (by increasing the selector expression degree by 1).
Resolve https://github.com/privacy-scaling-explorations/zkevm-specs/issues/231

Update EndBlock spec; update tx_table

---

specs/tables.md
src/zkevm_specs/evm/table.py
src/zkevm_specs/state.py

Added `proof_type` instead of `field_tag` into MPT lookup.
`proof_type` can be:
```
IsStorageMod
IsNonceMod
IsBalanceMod
IsCodeHashProof
IsAccountDeleteMod
IsNonExistingAccountProof
```

MPT lookup proof type selectors

---

specs/tables.md

In the previous PR, we inserted the Keccak table section right in the middle of the MPT table section. In this PR we move the Keccak table to a new section.

minor: fix keccak table section

---

specs/tables.md
src/zkevm_specs/evm/table.py
src/zkevm_specs/state.py

- Add AccountFieldType.NonExisting in order to perform lookups from the EVM circuit that use non-existing proofs (for accounts) from the MPT Circuit via the State circuit.
- Add MPTProofType.NonExistingStorageProof so that the MPT Circuit can prove non-existence of storage keys.
- Update State Circuit to transparently use MPTProofType.NonExistingStorageProof for Storage entries when  the MPT Lookup has committedValue == 0 and value == 0.
The change that makes the State Circuit support non-existing proofs on the Storage Tag will require 2 IsZero gadgets (which require a column each).  I'm not sure if there is any free column to be reused on Storage rows in the State Circuit, or 2 new columns need to be allocated.
I believe non-existence storage proofs support can be handled in 3 different …

Support non-existing proofs in RwTable

---

specs/exp-proof-design-doc.md
specs/exp-proof.md
specs/exponentiation-circuit.md
specs/opcode/0AEXP.md
specs/tables.md
src/zkevm_specs/__init__.py
src/zkevm_specs/evm/execution/__init__.py
src/zkevm_specs/evm/execution/exp.py
src/zkevm_specs/evm/instruction.py
src/zkevm_specs/evm/table.py
src/zkevm_specs/evm/typing.py
src/zkevm_specs/exp_circuit.py
src/zkevm_specs/util/arithmetic.py
src/zkevm_specs/util/constraint_system.py
src/zkevm_specs/util/param.py
tests/evm/test_exp.py

* Design Document: https://hackmd.io/@rohitnarurkar/BJhpYGiCc
* Circuits Implementation: https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/700
This PR implements the following:
The `EXP` opcode computes the exponentiation result of an integer base to an integer exponent:
```
base ^ exponent == exponentiation (mod 2^256)
```
The  exponentiation circuit verifies the exponentiation trace, i.e. intermediate multiplication steps generated by the [Exponentiation by Squaring](https://hackmd.io/@rohitnarurkar/BJhpYGiCc#Background) algorithm.
The `EXP` opcode gadget does lookups (conditional based on the `exponent` value) to the exponentiation table.

Exponentiation circuit and EXP opcode

---

specs/exp-proof.md

Changed tab for space, fixed bullet indentation

Fix bad indentation in the `EXP` spec doc

---

src/zkevm_specs/evm/execution/exp.py

We define a boolean variable `single_step` where:
- `single_step == 1 if exponent == 2`
- `single_step == 0 if exponent > 2`
We don't need any additional constraints on `single_step` (not even `require_boolean`) because it is simply used to do a lookup to the exponentiation circuit. All necessary constraints on that column (`exp_circuit.exp_table.is_last`) are handled within the exponentiation circuit.
This makes the [specs gadget](https://github.com/scroll-tech/zkevm-specs/blob/fix/exp-circuit-compat/src/zkevm_specs/evm/execution/exp.py#L25-L34) compatible with the [circuits gadget](https://github.com/scroll-tech/zkevm-circuits/blob/feat/exp/zkevm-circuits/src/evm_circuit/execution/exp.rs#L130-L167)
@adria0 This is the last pending PR before we can get …

fix: make exp gadget compatible with circuits impl

---

src/zkevm_specs/public_inputs.py

- In this PR, we aim to reduce the num of rows used by `raw_public_input`(abbr. rpi) col by adding constraints on tx_table. The length of the `rpi` col is reduced from 
> `BLOCK_LEN + 1 + 3 * (TX_LEN * MAX_TXs + 1) + 3 * MAX_CALLDATABYTES` to
> `BLOCK_LEN + 1 + 3 * (TX_LEN * MAX_TXs + 1) + MAX_CALLDATABYTES`. 
The current circuit includes the `tx_id` and `index` part of the calldata bytes in the raw public input col which is not necessary 
as these fields has good simple pattern. 
|tx_id | tag | index | value |
|-|-|-|-|
| 1 | CallData | 1 | tx[0].data[0] |
| 1 | CallData | 2 | tx[0].data[1] |
|... | CallData | .. | tx[0].data[..] |
| 2 | CallData | 1 | tx[1].data[0] |
| 2 | CallData | 2 | tx[1].data[1] |
|... | CallData | .. | tx[..].data[..] |
| 0 | CallData | 0 | 0 |
| 0 | CallData | 0 …

PublicInput circuit: reduce the length of raw public input column

---

src/zkevm_specs/evm/instruction.py
src/zkevm_specs/evm/step.py
src/zkevm_specs/evm/table.py
src/zkevm_specs/evm/typing.py

As [an error report](https://github.com/privacy-scaling-explorations/zkevm-specs/actions/runs/3426588988/jobs/5708575463) from CI:
```
...: PEP 484 prohibits implicit Optional.
...: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
```
Follow the instruction of [no_implicit_optional](https://github.com/hauntsaninja/no_implicit_optional) to fix with script as:
```
pip install no_implicit_optional
no_implicit_optional src/
no_implicit_optional tests/
```

fix `no_implicit_optional` in CI

---

specs/opcode/3fEXTCODEHASH.md
src/zkevm_specs/evm/execution/balance.py
src/zkevm_specs/evm/execution/extcodehash.py
tests/evm/test_balance.py
tests/evm/test_extcodehash.py

According to previous `BALANCE` PR https://github.com/privacy-scaling-explorations/zkevm-specs/pull/248, fix this opcode to use non-existing proof for account existence check.

Fix opcode `EXTCODEHASH` to use non-existing proof for account existence

---

src/zkevm_specs/public_inputs.py
src/zkevm_specs/state.py
src/zkevm_specs/tx.py
src/zkevm_specs/util/arithmetic.py

For an `n-ary` number, each digit should be in range `[0, n)`

reinforce linear_combine

---

specs/opcode/3bEXTCODESIZE.md
src/zkevm_specs/evm/execution/__init__.py
src/zkevm_specs/evm/execution/extcodesize.py
tests/evm/test_extcodesize.py

Close https://github.com/privacy-scaling-explorations/zkevm-specs/issues/327
It is similar as [EXTCODEHASH](https://github.com/privacy-scaling-explorations/zkevm-specs/pull/305) and [BALANCE](https://github.com/privacy-scaling-explorations/zkevm-specs/pull/248) (used `exists` witness value).

Spec for opcode `EXTCODESIZE`

---

specs/opcode/F1CALL_F2CALLCODE_F4DELEGATECALL_FASTATICCALL.md
src/zkevm_specs/evm/execution/callop.py
tests/evm/test_callop.py

Close https://github.com/privacy-scaling-explorations/zkevm-specs/issues/334
Related circuit PR https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/973
As issue described, there should be no `transfer` invocation for call related opcodes (except [CALL](https://github.com/ethereum/go-ethereum/blob/master/core/vm/evm.go#L167)) - [CALLCODE](https://github.com/ethereum/go-ethereum/blob/master/core/vm/evm.go#L253), [DELEGATECALL](https://github.com/ethereum/go-ethereum/blob/master/core/vm/evm.go#L301) and [STATICCALL](https://github.com/ethereum/go-ethereum/blob/master/core/vm/evm.go#L340).
~~And callee balance is also needed for checking account existence below (for now). Suppose if it could be fixed to replace with [non-existing …

Bug: fix to not invoke `transfer` for call related opcodes (except `CALL`)

---

src/zkevm_specs/state.py
tests/test_state_circuit.py

Close https://github.com/privacy-scaling-explorations/zkevm-specs/issues/275
I did following things in this PR.
- Add `lexicographic_ordering_selector` flag to Row and Operation
- Fix [check_start](https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/src/zkevm_specs/state.py#L171) constraints
The circuit constraints and logics are aligned with zkevm-circuits.
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/state_circuit/constraint_builder.rs
I would appreciate it if you could confirm.
Thank you.

State circuit "start" tag constraints fix

---

specs/opcode/3cEXTCODECOPY.md
src/zkevm_specs/evm/execution/extcodecopy.py
tests/evm/test_extcodecopy.py

As of #259  adds non-existence check for opcode EXTCODECOPY.

Add non-existing check to EXTCODECOPY

---

specs/bytecode-proof.md

Some things that were corrected during the review of https://github.com/privacy-scaling-explorations/zkevm-specs/pull/340 were only corrected in the python code but not in the markdown document.
Perhaps it is ok to merge this with only one review

Correction on bytecode circuit

---

src/zkevm_specs/state.py

Close https://github.com/privacy-scaling-explorations/zkevm-specs/issues/244
I added following constraint.
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/e74c5e7680bd5e4cb089aeb1d6a389e050a8169c/zkevm-circuits/src/state_circuit/constraint_builder.rs#L319
I would appreciate it if you could confirm.
Thank you.

Specify constraints for TxRefund in State circuit

---

specs/evm-proof.md
specs/opcode/31BALANCE.md
specs/opcode/3bEXTCODESIZE.md
specs/opcode/3cEXTCODECOPY.md
specs/opcode/3fEXTCODEHASH.md
specs/tables.md
src/zkevm_specs/evm/execution/balance.py
src/zkevm_specs/evm/execution/callop.py
src/zkevm_specs/evm/execution/extcodecopy.py
src/zkevm_specs/evm/execution/extcodehash.py
src/zkevm_specs/evm/execution/extcodesize.py
src/zkevm_specs/evm/main.py
src/zkevm_specs/state.py
tests/evm/test_balance.py
tests/evm/test_callop.py
tests/evm/test_extcodecopy.py
tests/evm/test_extcodehash.py
tests/evm/test_extcodesize.py

Change the approach to handle non-existing accounts by
1. Using `code_hash = 0` as a non-existing account state
2. Doing accont non-existence MPT proofs from the State Circuit on the where an account update is CodeHash and goes 0->0.
Resolve https://github.com/privacy-scaling-explorations/zkevm-specs/issues/259

feat: update account non-existence handling

---

src/zkevm_specs/evm/execution/shl_shr.py

The fix to the issue https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1124 has been implemented in the circuit in https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1125/.
This PR syncs the fix to the spec.

bug: add shf0 == shift.cells[0] constraint to shlshr

---

specs/error_state/ErrorStackOverflow_Underflow.md
src/zkevm_specs/evm/execution/error_stack.py
src/zkevm_specs/evm/instruction.py
src/zkevm_specs/evm/opcode.py
src/zkevm_specs/evm/table.py

This PR aims to simplify `ErrorStack` by using lookup to `FixedTable`. While reviewing other PRs I found out that the `ErrorStack` is not using `ResponsibleOpcode`, which already contains invalid stack pairs `(opcode, stack_pointer)` for quick lookup.
https://github.com/privacy-scaling-explorations/zkevm-specs/blob/f569eef524f4a19814b4a36cb081c9a9718a54dc/src/zkevm_specs/evm/execution_state.py#L354-L355
The circuit will need to be updated to have the `stack_{under,over}flow_pairs` for this simplification.

Simplify `ErrorStack`

---

specs/error_state/ErrorOutOfGasSloadSstore.md
src/zkevm_specs/evm/execution_state.py

Close https://github.com/privacy-scaling-explorations/zkevm-specs/issues/382
Circuit impl PR https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1147
For `SLOAD` gas calculation with EIP-2929 could reference [this go-ethereum function](https://github.com/ethereum/go-ethereum/blob/fd4230f695247102c249d5ece2c7f6760350ae6f/core/vm/operations_acl.go#L103
).
And for `SSTORE` gas calculation with EIP-3529 could reference [this go-ethereum function](https://github.com/ethereum/go-ethereum/blob/fd4230f695247102c249d5ece2c7f6760350ae6f/core/vm/operations_acl.go#L27).

Markdown doc for `ErrorOutOfGasSloadSstore` state

---

specs/error_state/ErrorOutOfGasEXP.md

Add Markdown doc for `EXP` OOG eror.
Gas calculation could reference [this go-ethereum function](https://github.com/ethereum/go-ethereum/blob/master/core/vm/gas_table.go#L351).
Circuit PR https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1232

Markdown doc for `ErrorOutOfGasEXP` state

---

src/zkevm_specs/evm/table.py
src/zkevm_specs/evm/typing.py

The CI failed because of mypy version upgrade.
https://github.com/privacy-scaling-explorations/zkevm-specs/actions/runs/4350682083/jobs/7601683721
```
$ pip3 install mypy --upgrade
```
```shell
Collecting mypy>=0.931
Downloading mypy-1.1.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.1 MB)
```
`fields` function argument should be DataclassInstance.
https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/src/zkevm_specs/evm/table.py#L366
Adding `@dataclass(frozen=True)` to `TableRow`, `CopyCircuitRow` and `ExpCircuitRow`.
Modifying frozen dataclass state with `dataclasses.replace`.
I would be happy if you could confirm or suggest better solution.

fix latest typing error

---

src/zkevm_specs/evm_circuit/execution/sar.py
src/zkevm_specs/evm_circuit/execution/shl_shr.py

1. Add `shf_lt256` to `ShlShrGadget` as this circuit PR https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1151
2. Also add `shf_lt256` to `SarGadget` as code https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/execution/sar.rs#L54
3. Add `shf_div64 < 4` constraint to `SarGadget` as PR https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1272

Synchronize `SHL`, `SHR` and `SAR` fixes from zkevm-circuits

---

specs/error_state/ErrorOutOfGasLog.md

- markdown spec for oog log error
- TODO: add python code will add after circuit https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1116 merges.

md spec for oog log error

---

src/zkevm_specs/evm_circuit/typing.py
src/zkevm_specs/exp_circuit.py
tests/evm/test_exp.py

This is https://github.com/privacy-scaling-explorations/zkevm-specs/pull/359 updated to resolve conflicts.
Implements the padding strategy for the Exp Circuit that doesn't require new constraints by adding dummy valid single-step exponentiation to fill the circuit.

Implement Exp Circuit padding strategy

---

specs/tables.md
src/zkevm_specs/evm_circuit/execution/address.py
src/zkevm_specs/evm_circuit/execution/begin_tx.py
src/zkevm_specs/evm_circuit/execution/block_ctx.py
src/zkevm_specs/evm_circuit/execution/caller.py
src/zkevm_specs/evm_circuit/execution/callop.py
src/zkevm_specs/evm_circuit/execution/create.py
src/zkevm_specs/evm_circuit/execution/dataCopy.py
src/zkevm_specs/evm_circuit/execution/end_block.py
src/zkevm_specs/evm_circuit/execution/end_tx.py
src/zkevm_specs/evm_circuit/execution/log.py
src/zkevm_specs/evm_circuit/execution/origin.py
src/zkevm_specs/evm_circuit/execution/return_revert.py
src/zkevm_specs/evm_circuit/execution/selfbalance.py
src/zkevm_specs/evm_circuit/execution/storage.py
src/zkevm_specs/evm_circuit/typing.py
tests/evm/test_address.py
tests/evm/test_begin_tx.py
tests/evm/test_caller.py
tests/evm/test_callop.py
tests/evm/test_create.py
tests/evm/test_dataCopy.py
tests/evm/test_logs.py
tests/evm/test_return_revert.py
tests/evm/test_selfbalance.py
tests/evm/test_sload.py
tests/evm/test_sstore.py

When encoding an Address into columns that support Words and other types, split the Address into lo/hi instead of keeping the whole word in the lo part.  This makes it easier to reason about always having lo/hi values be at most 128 bits.
Resolve https://github.com/privacy-scaling-explorations/zkevm-specs/issues/423
Note that we still have some Address encoded as a single field.  This happens for example:
- In the RwTable we use Address key as single field value in `TxAccessListAccount`, `TxAccessListAccountStorage`, `Account`, `AccountStorage`
- The MPT Table each proof type has an `Address` key field
This means we still have some conversion from Address as Word to Address as Field and vice versa.  Nevertheless I think favoring  Address as Word where possible is more optimal, because …

Split Address when stored in Word 

---

Makefile
src/zkevm_specs/evm_circuit/execution/begin_tx.py
src/zkevm_specs/evm_circuit/execution/callop.py
src/zkevm_specs/evm_circuit/execution/create.py
src/zkevm_specs/evm_circuit/instruction.py

I've searched for other projects using mypy encountering similar issues (not all files are checked) and I found that setting the `MYPATH` env var helps.  With this new type errors popped up, which I fixed in this PR.
Resolve https://github.com/privacy-scaling-explorations/zkevm-specs/issues/429

Make sure mypy checks all files

---

specs/tables.md
src/zkevm_specs/copy_circuit.py
src/zkevm_specs/evm_circuit/instruction.py
src/zkevm_specs/evm_circuit/table.py
src/zkevm_specs/evm_circuit/typing.py
tests/evm/test_end_block.py

> 
These files are:
- src/zkevm_specs/evm_circuit/table.py
- src/zkevm_specs/evm_circuit/typing.py
- src/zkevm_specs/evm_circuit/instruction.py
- src/zkevm_specs_/copy_circuit.py
- specs/tables.md
- tests/evm/test_end_block.py
No other appearance of RwTableTag found. RwTable stayed untouched.

Changed name of RwTableTag to Target (#422)

---

src/zkevm_specs/evm_circuit/execution/begin_tx.py
src/zkevm_specs/evm_circuit/execution/end_tx.py
src/zkevm_specs/evm_circuit/instruction.py

- Added zero equality constraint for `quotient_hi`
- Fix to return with `product_bytes` which was there but unused
As mentioned in https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/util/math_gadget/mul_word_u64.rs#L15-L16, `mul_word_by_u64` gadget assumes that there will be no overflow.
And this is implicitly checked in [the code below](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/util/math_gadget/mul_word_u64.rs#L50-L53).
However, there is no such constraint inside the `mul_word_by_u64` gadget, but instead it returns the carry and checks outside the gadget. I think this is an inconsistent (with the zkevm-circuits code) implementation, so I made the fix.
Sorry for the weird …

refactor `mul_word_by_u64` gadget

---

src/zkevm_specs/evm_circuit/execution/push.py
src/zkevm_specs/evm_circuit/execution/stop.py

Linked to issue #463 
------------ Objective
We intend here to support PUSHn with bytecode length inferior to n.
------------ Rational
In pushn, "selectors" are switches to enable or disable lookup arguments on the bytcode bytes as well as to check whether these are non-null if needs be. They directly depend on "n" of PUSHn.
We add to these "selectors", "counters" which have similar role but are a subset of them depending on the bytecode length. We added these extra switches to be able to easily check the various identities at the risk of some redundancy.
To support these changes, modifications in stop.py also had to be done. More precisely, the check "is_out_of_range had to be extended to support small bytecodes.

Fully implement PUSHn

---

specs/error_state/ErrorGasUintOverflow.md
specs/error_state/ErrorOutOfGasCall.md
specs/error_state/ErrorOutOfGasCreate.md
specs/error_state/ErrorOutOfGasDynamicMemoryExpansion.md
specs/opcode/F0CREATE_F5CREATE2.md
src/zkevm_specs/evm_circuit/execution/__init__.py
src/zkevm_specs/evm_circuit/execution/begin_tx.py
src/zkevm_specs/evm_circuit/execution/create.py
src/zkevm_specs/evm_circuit/execution/error_gas_uint_overflow.py
src/zkevm_specs/evm_circuit/execution/error_oog_create.py
src/zkevm_specs/evm_circuit/execution/error_oog_dynamic_memory_expansion.py
src/zkevm_specs/evm_circuit/execution_state.py
src/zkevm_specs/evm_circuit/instruction.py
src/zkevm_specs/util/param.py
tests/evm/test_begin_tx.py
tests/evm/test_create.py
tests/evm/test_error_gas_uint_overflow.py
tests/evm/test_error_oog_create.py
tests/evm/test_error_oog_dynamic_memory_expansion.py

closed #454 and #459
---
[EIP-3860](https://eips.ethereum.org/EIPS/eip-3860#rules) includes
- limit the max size of init code to `49152` 
- add extra gas required for init code, `2 * len(ceil(init_code/32))`
This PR includes
1. move `CREATE/2` oog from `error_oog_dynamic_memory_expansion.py` to `error_oog_create.py`
2. support EIP-3860
- `create.py` add  extra gas cost for init code. 
- `begin_tx.py` add  extra gas cost for init code
- `error_oog_create.py` handles errors of oog and max size of init code  (see [Rules 1 and 3](https://eips.ethereum.org/EIPS/eip-3860#rules)).    
- `error_gas_uint_overflow.py` handles extra gas required for init code

Feat/#454 implement ErrorOutOfGasCreate error state

---

specs/bytecode-proof.md
specs/copy-proof.md
specs/evm-proof.md
specs/opcode/5AGAS.md

This pull request includes several updates to the ZK-EVM specifications documentation. The main change is in `bytecode-proof.md`, where the definition of `push_data_left` has been made clearer. Previously, the description read, "The number of left bytes data needs to be PUSHed," which was somewhat incomprehensible. Other minor grammar and clarity fixes are included in different parts of the documentation.
1. **4302df1**: Updated the description of `push_data_left` for better clarity.
2. **1225a85**: Fixed a spelling error in `opcode/5AGAS.md`.
3. **60d3c05**: Improved grammar in `copy-proof.md`.
4. **5754ad8**: Corrected grammar in `evm-proof.md`.
I've updated the definition of `push_data_left` to make it easier to understand as I found hard to interpret. It'd be great if you could check …

Documentation Improvements in ZK-EVM Specs

---

specs/precompile/06ecAdd.md
specs/precompile/08ecPairing.md
src/zkevm_specs/ecc_circuit.py
src/zkevm_specs/evm_circuit/execution/__init__.py
src/zkevm_specs/evm_circuit/execution/precompiles/ecadd.py
src/zkevm_specs/evm_circuit/execution/precompiles/ecpairing.py
src/zkevm_specs/util/ec.py
tests/evm/precompiles/test_ecPairing.py
tests/test_ecc_circuit.py

feat/#325 precomiple ecPairing

---

specs/error_state/ErrorOutOfGasTloadTstore.md
specs/evm-proof.md
specs/opcode/92TLOAD_93TSTORE.md
specs/state-proof.md

Specs for TLOAD TSTORE

---

specs/tables.md

We reviewed the copy table usage recently. We add the missing copies to the table.md

Add all instances of copy table copy
