privacy-scaling-explorations/zkevm-specs

- specs/word-encoding.md
- src/encoding/addition.py
Fix #14
We specify the endianness and add more examples to improve the readability.
> Improve addition

- specs/word-encoding.md
Elaborate on why we can't do 256 bits directly
> add barry's edit

- specs/evm-proof.md
- specs/state-proof.md
The WIP PR aims to spec out the state proof and evm proof.
> [WIP] State and EVM proof

- specs/opcode/90SWAPX.md
Per the circuit code discussion https://github.com/appliedzkp/zkevm-circuits/pull/108#discussion_r733309980, specifying out the underflow condition and the check required seems valuable.
> add underflow condition

- specs/opcode/51MLOAD_52MSTORE_53MSTORE8.md
- src/zkevm_specs/opcode/__init__.py
- src/zkevm_specs/opcode/mload_mstore.py
- tests/test_memory.py
Implementation: https://github.com/appliedzkp/zkevm-circuits/pull/160
> MSTORE8 opcode spec

- .gitignore
- README.md
- specs/opcode/56JUMP.md
- specs/opcode/57JUMPI.md
- src/zkevm_specs/evm/execution/__init__.py
- src/zkevm_specs/evm/execution/jump.py
- src/zkevm_specs/evm/execution/jumpi.py
- src/zkevm_specs/evm/instruction.py
- src/zkevm_specs/evm/main.py
- tests/evm/test_jump.py
- tests/evm/test_jumpi.py
The spec code is still WIP. We can review the design doc first:
https://hackmd.io/IejTyRxyQmGM5NTr-OuYyg?view=
> JUMP and JUMPI spec

- specs/tables.md
I've included the updates from https://github.com/appliedzkp/zkevm-specs/pull/88 in the tables.
> Add tables documentation

- specs/opcode/32ORIGIN.md
- src/zkevm_specs/evm/execution/__init__.py
- src/zkevm_specs/evm/execution/origin.py
- tests/evm/test_origin.py
> Add `ORIGIN` opcode spec

- src/zkevm_specs/evm/execution/storage.py
- src/zkevm_specs/evm/instruction.py
close https://github.com/appliedzkp/zkevm-specs/issues/123
> use constraints for `sload` & `sstore` gas

- specs/opcode/3fEXTCODEHASH.md
- src/zkevm_specs/evm/execution/extcodehash.py
- tests/evm/test_extcodehash.py
Update specs for EXTCODEHASH to match its implementation in https://github.com/appliedzkp/zkevm-circuits/pull/353
> Update EXTCODEHASH to handle reverts

- specs/tables.md
- src/zkevm_specs/state.py
- tests/test_state_circuit.py
Fixes https://github.com/appliedzkp/zkevm-specs/issues/160
> Move stack and memory addresses from key3 to key2

- specs/opcode/39CODECOPY.md
- specs/opcode/CopyCodeToMemory.md
- src/zkevm_specs/bytecode.py
- src/zkevm_specs/evm/execution/__init__.py
- src/zkevm_specs/evm/execution/calldatacopy.py
- src/zkevm_specs/evm/execution/codecopy.py
- src/zkevm_specs/evm/execution/copy_code_to_memory.py
- src/zkevm_specs/evm/execution/memory_copy.py
- src/zkevm_specs/evm/execution_state.py
- src/zkevm_specs/evm/instruction.py
- src/zkevm_specs/evm/step.py
- src/zkevm_specs/evm/table.py
- src/zkevm_specs/evm/typing.py
- src/zkevm_specs/util/param.py
- tests/evm/test_calldatacopy.py
- tests/evm/test_codecopy.py
- tests/test_bytecode_circuit.py
Circuits PR: https://github.com/appliedzkp/zkevm-circuits/pull/391
> CODECOPY opcode

- src/zkevm_specs/evm/instruction.py
- src/zkevm_specs/evm/typing.py
- src/zkevm_specs/state.py
- tests/test_state_circuit.py
in circuit implementation there are some minor changes to raw spec, do update in this PR .  
circuit implementation:  https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/552
> revise log state constrain according to circuit implementation 

- Makefile
- setup.cfg
- src/zkevm_specs/copy_circuit.py
- src/zkevm_specs/evm/execution/begin_tx.py
- src/zkevm_specs/evm/execution/bitwise.py
- src/zkevm_specs/evm/execution/block_ctx.py
- src/zkevm_specs/evm/execution/calldatacopy.py
- src/zkevm_specs/evm/execution/calldataload.py
- src/zkevm_specs/evm/execution/codecopy.py
- src/zkevm_specs/evm/execution/extcodehash.py
- src/zkevm_specs/evm/execution/iszero.py
- src/zkevm_specs/evm/execution/log.py
- src/zkevm_specs/evm/step.py
- src/zkevm_specs/evm/typing.py
- src/zkevm_specs/opcode/stack.py
- src/zkevm_specs/public_inputs.py
- src/zkevm_specs/tx.py
- src/zkevm_specs/util/testing.py
Introduce flake8 but only enable the import check.
> Lint unused import

- specs/opcode/30ADDRESS.md
- src/zkevm_specs/evm/execution/__init__.py
- src/zkevm_specs/evm/execution/address.py
- tests/evm/test_address.py
Circuit: https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/680
> Spec for opcode `ADDRESS`

- specs/opcode/40BLOCKHASH.md
- src/zkevm_specs/evm/execution/__init__.py
- src/zkevm_specs/evm/execution/blockhash.py
- tests/evm/test_blockhash.py
Not sure for handling valid range. If there is any appropriate way for checking valid range, please let me know.
Thank you.
> Add spec for `BLOCKHASH` opcode

- specs/opcode/38CODESIZE.md
- specs/opcode/3dRETURNDATASIZE.md
- src/zkevm_specs/evm/execution/__init__.py
- src/zkevm_specs/evm/execution/returndatasize.py
- tests/evm/test_returndatasize.py
I added RETURNDATASIZE opcode and modified missing link.
I would appreciate it if you could confirm.
Thank you.
> Add spec for RETURNDATASIZE opcode

- specs/opcode/39CODECOPY.md
- specs/opcode/3cEXTCODECOPY.md
- src/zkevm_specs/evm/execution/__init__.py
- src/zkevm_specs/evm/execution/extcodecopy.py
- tests/evm/test_extcodecopy.py
I wrote the spec for `EXTCODECOPY` opcode.
I'm not sure about that the codehash read from `address` should be stored in `bytecode_table`.
Also there could be some mistakes since it's my first contribution to the project. 
Please give me many comments. Thanks!
> Write `EXTCODECOPY` spec

- src/zkevm_specs/public_inputs.py
- tests/test_public_inputs.py
- Add 0 row in `tx_table` and `block_table`
- Update selectors `q_end`, `q_not_end`
- Update field names to match MD spec
> Update Public Input circuit 

- specs/transactions-proof.md
This PR aims to add some more descriptions to spec of Tx circuit in respect to the changes made in https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/803
> Update Tx circuit spec

- src/zkevm_specs/evm/execution/oog_constant.py
- src/zkevm_specs/evm/execution/stop.py
- tests/evm/test_oog_constant.py
- tests/evm/test_stop.py
according to issue https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/815, remove IsPersistent.
> remove IsPersistent from Stop & oog constant

- specs/opcode/F1CALL_F2CALLCODE_F4DELEGATECALL_FASTATICCALL.md
- src/zkevm_specs/evm/execution/__init__.py
- src/zkevm_specs/evm/execution/callop.py
- src/zkevm_specs/evm/execution_state.py
- tests/evm/test_callop.py
Close https://github.com/privacy-scaling-explorations/zkevm-specs/issues/306
Referenced [go-ethereum CALLCODE implmentation](https://github.com/ethereum/go-ethereum/blob/d30e39b2f833fb75f1e529cd405061fb6b548b8d/core/vm/evm.go#L283)
Circuit PR https://github.com/scroll-tech/zkevm-circuits/pull/218
> Spec for opcode `CALLCODE`

- src/zkevm_specs/evm/execution/oog_call.py
- src/zkevm_specs/evm/instruction.py
- src/zkevm_specs/evm/typing.py
- tests/evm/test_oog_call.py
-  update to read tx account access list instead of write , circuit PR https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/827
> update spec to match oog call circuit

- specs/bytecode-proof.md
- src/zkevm_specs/bytecode.py
- src/zkevm_specs/evm/instruction.py
- src/zkevm_specs/evm/table.py
- src/zkevm_specs/evm/typing.py
- tests/test_bytecode_circuit.py
Closes https://github.com/privacy-scaling-explorations/zkevm-specs/issues/151
> Refactor bytecode circuit

- src/zkevm_specs/evm/execution/callop.py
- src/zkevm_specs/evm/execution/oog_call.py
- src/zkevm_specs/evm/util/call_gadget.py
- tests/evm/test_callop.py
- tests/evm/test_oog_call.py
It's for [CALL & CALL OOG refactor #940](https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/940)
> refacor/CALL and OOG_CALL

- src/zkevm_specs/bytecode.py
- src/zkevm_specs/evm/execution/addmod.py
- src/zkevm_specs/evm/execution/begin_tx.py
- src/zkevm_specs/evm/execution/byte.py
- src/zkevm_specs/evm/execution/callop.py
- src/zkevm_specs/evm/execution/end_block.py
- src/zkevm_specs/evm/execution/mulmod.py
- src/zkevm_specs/evm/instruction.py
- src/zkevm_specs/public_inputs.py
- tests/test_bytecode_circuit.py
- tests/test_memory.py
- tests/test_state_circuit.py
Close https://github.com/privacy-scaling-explorations/zkevm-specs/issues/370
Fix format issue as [CI action](https://github.com/privacy-scaling-explorations/zkevm-specs/actions/runs/4072380664/jobs/7015076517). Since black is upgraded to `23.1.0`.
> fix: reformat with `black-23.1.0`

- specs/bytecode-proof.md
- specs/copy-proof.md
- specs/evm-proof.md
- specs/public_inputs.md
- specs/super_circuit.md
- specs/transactions-proof.md
- specs/word-encoding.md
> Fix: typos

- specs/state-proof.md
- src/zkevm_specs/state_circuit.py
Adding bullet points to break lines in description. 
There is no line breaks in the current doc as below.
> doc/reformat state-proof.md

- specs/error_state/ErrorCodeStore.md
spec issue #394 
circuit PR is https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1265
> spec for codestore error

- specs/error_state/ErrorOutOfGasMemoryCopy.md
- src/zkevm_specs/evm_circuit/execution_state.py
Circuit PR https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1288
> Markdown doc for `ErrorOutOfGasMemoryCopy` state

- specs/error_state/error_write_protection.md
- add hackmd for write protection error
- TODO: add python code after circuit pr (https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1001) merged.
> spec for write protection error

- specs/state-proof.md
Resolve https://github.com/privacy-scaling-explorations/zkevm-specs/issues/425
I noticed that we already had some documentation in https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/specs/evm-proof.md#account-non-existence so I've added a link to that section in the new paragraph.
> Document Account and Storage rws in RwTable

- src/zkevm_specs/evm_circuit/execution/create.py
- tests/evm/test_create.py
> feat/#443 handle ErrorContractAddressCollision for create

- src/zkevm_specs/evm_circuit/execution/__init__.py
- src/zkevm_specs/evm_circuit/execution/error_oog_exp.py
- tests/evm/test_error_oog_exp.py
> Feat/#449 implement ErrorOutOfGasEXP error state

- src/zkevm_specs/evm_circuit/execution/push.py
- src/zkevm_specs/evm_circuit/execution_state.py
- src/zkevm_specs/evm_circuit/opcode.py
- src/zkevm_specs/evm_circuit/typing.py
- tests/evm/test_error_invalid_opcode.py
- tests/evm/test_push.py
- tests/test_bytecode_circuit.py
Close https://github.com/privacy-scaling-explorations/zkevm-specs/issues/435
zkevm-circuits PR https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1463
> Implement `PUSH0` instruction

- specs/error_state/ErrorOutOfGasSloadSstore.md
- src/zkevm_specs/evm_circuit/execution/__init__.py
- src/zkevm_specs/evm_circuit/execution/error_oog_sload_sstore.py
- src/zkevm_specs/evm_circuit/instruction.py
- src/zkevm_specs/evm_circuit/typing.py
- src/zkevm_specs/util/param.py
- tests/evm/test_error_oog_sload_store.py
> Feat/#453 Implement ErrorOutOfGasSSTORE/ErrorOutOfGasSLOAD error state

- specs/error_state/ErrorOutOfGasStaticMemoryExpansion.md
- src/zkevm_specs/evm_circuit/execution/__init__.py
- src/zkevm_specs/evm_circuit/execution/error_oog_static_memory_expansion.py
- tests/evm/test_error_oog_static_memory_expansion.py
> feat/#455 impl ErrorOutOfGasStaticMemoryExpansion error state

- specs/error_state/ErrorCodeStore.md
- src/zkevm_specs/evm_circuit/execution/__init__.py
- src/zkevm_specs/evm_circuit/execution/error_code_store.py
- tests/evm/test_error_code_store.py
> Feat/#445 implement ErrorOutOfGasCodeStore and ErrorMaxCodeSizeExceeded error state

- specs/error_state/ErrorOutOfGasSHA3.md
- src/zkevm_specs/evm_circuit/execution/__init__.py
- src/zkevm_specs/evm_circuit/execution/error_oog_sha3.py
- tests/evm/test_error_oog_sha3.py
> Feat/#450 implement ErrorOutOfGasSha3 error state

- specs/error_state/ErrorReturnDataOutOfBound.md
- src/zkevm_specs/evm_circuit/execution/__init__.py
- src/zkevm_specs/evm_circuit/execution/error_return_data_out_of_bound.py
- tests/evm/test_error_return_data_out_of_bound.py
updated version of #366 and closed #446
> Feat/#446 implement ErrorReturnDataOutOfBound error state

- specs/error_state/ErrorCodeStore.md
- specs/error_state/ErrorInvalidCreationCode.md
- src/zkevm_specs/evm_circuit/execution/__init__.py
- src/zkevm_specs/evm_circuit/execution/error_invalid_creation_code.py
- src/zkevm_specs/util/param.py
- tests/evm/test_error_invalild_creation_code.py
and updated version of #400 and closed #434
> Feat/#434 Implement ErrorInvalidCreationCode error state

- src/zkevm_specs/evm_circuit/execution/error_gas_uint_overflow.py
- src/zkevm_specs/evm_circuit/execution/error_invalid_jump.py
- src/zkevm_specs/evm_circuit/execution/error_invalid_opcode.py
- src/zkevm_specs/evm_circuit/execution/error_oog_call.py
- src/zkevm_specs/evm_circuit/execution/error_oog_constant.py
- src/zkevm_specs/evm_circuit/execution/error_oog_log.py
- src/zkevm_specs/evm_circuit/execution/error_stack.py
- src/zkevm_specs/evm_circuit/execution/error_write_protection.py
> feat/#472 rw counter delta should include reversible_write_counter in error cases

- specs/opcode/41COINBASE_45GASLIMIT_48BASEFEE.md
- specs/public_inputs.md
- specs/tables.md
- src/zkevm_specs/evm_circuit/execution/block_ctx.py
- src/zkevm_specs/evm_circuit/execution_state.py
- src/zkevm_specs/evm_circuit/opcode.py
- src/zkevm_specs/evm_circuit/table.py
- src/zkevm_specs/evm_circuit/typing.py
- src/zkevm_specs/pi_circuit.py
- tests/evm/test_block_ctx.py
- tests/test_public_inputs.py
> feat/#437 rename difficulty to prev_randao

- src/zkevm_specs/evm_circuit/execution/begin_tx.py
- tests/evm/test_begin_tx.py
> feat/#457 support EIP-3651 warm coinbase

- specs/copy-proof.md
- specs/error_state/ErrorCodeStore.md
- specs/state-proof.md
- specs/super_circuit.md
- specs/tables.md
- specs/transactions-proof.md
Hello
I fixed some typos in the docs,
Hope it helps.
Br,
Tudor.
> fix: several typos in the docs

- specs/precompile/07ecMul.md
- src/zkevm_specs/ecc_circuit.py
- src/zkevm_specs/evm_circuit/execution/__init__.py
- src/zkevm_specs/evm_circuit/execution/precompiles/ecmul.py
- src/zkevm_specs/util/ec.py
- tests/evm/precompiles/test_ecMul.py
- tests/test_ecc_circuit.py
> Feat/#324 precompile ecMul

- specs/error_state/ErrorInvalidCreationCode.md
- specs/withdrawal-proof.md
<Description>
Several typos are fixed
> Fix: fix several minor typos

- specs/exp-proof.md
> chore(exp-proof.md): Update an invalid path

- specs/virtual_state/begin_tx.md
- specs/virtual_state/end_tx.md
Adding markdown spec for begin_tx & end_tx gadgets
> Add begin_tx and end_tx specs
